### ISSUE TITLE
(int)(input())の使い方について

### ISSUE THREAD

**Issue by pineapplehunter** [AstPy-ms/imashime#1]
コードを見ていると`(int)(input())`というコードを多く見かけました。
```python
(int)(input())
```
は
```python
int(input())
```
と同じで、`(int)`は型変換ではなく関数（クラス）intを()でくくっただけなので関数呼び出しをやっているのが明確な
```python
int(input())
```
のほうがいいと思います。

**Comment by astpy** [comment]
int(input())になってます。

**Comment by astpy** [comment]
なってませんでした。
でもそれらは先生方が書かれたありがたいコードなので、変更せずにそのままにします。
それも戒めです。

**Comment by pineapplehunter** [comment]
戒めなんですね。
わかりました。
